version: '3.8'

services:
  # 메인 Spring Boot 애플리케이션
  qrystal-app:
    build: .
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      - SPRING_PROFILES_ACTIVE=aws
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}  
      - DB_PASSWORD=${DB_PASSWORD}
      - JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_PASSWORD}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

