server:
  port: 81
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(KgM8OzzgPpdhF9G5XzzNIMR7xmVAERFPrphxa3X/MvX5TO4AHY6GsVFw2Cs9U1NQjTnNIHkjcAU8eWdz9C0HrbIEhL65fqU6)
    username: ENC(6R/c31GTSL0h+tEDEJr8pA==)
    password: ENC(qZRj27Us+5WqWEaxLwBuZ2by25Mpwf+eF2TsEMIdTys=)
  
  mvc:
    static-path-pattern: /**

  thymeleaf:
    prefix: classpath:/templates/    # 템플릿 위치
    suffix: .html                    # 확장자
    cache: false                     # 개발 환경에서는 false 권장
    encoding: UTF-8
    mode: HTML

  web:
    resources:
      static-locations: classpath:/static/

  redis:
    host: ${REDIS_SERVER_URL}
    port: 6379
    password: ${REDIS_PASSWORD}

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

logging:
  config: classpath:logback-spring.xml
  level:
    com.qrystal.admin: DEBUG

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWithMD5AndDES